"""Regenerate provision.json: a GPT template before and after provisioning.

Run from the repository root with the image-tools virtualenv:
    Images/tools/.venv/bin/python Images/tools/tests/fixtures/gpt/build_gpt_fixture.py

The fixture stores only the non-zero 512-byte sectors of each disk, in
base64, so ImageCore's Swift GPTDisk tests can rebuild both disks and
compare their own result with the Python one byte for byte.
"""

from __future__ import annotations

import base64
import io
import json
import uuid
from pathlib import Path

from apkrun_image.gpt import (
    ALIGNMENT,
    SECTOR_SIZE,
    GptPartition,
    disk_guid,
    partition_guid,
    provision_disk,
    write_gpt,
)

OUTPUT = Path(__file__).with_name("provision.json")
IMAGE_VERSION = "2026.10.0-fixture"
ROLE = "userdata"
INSTANCE = uuid.UUID("3f2504e0-4f89-41d3-9a0c-0305e82c3301")
OLD_SIZE = 3 * ALIGNMENT
NEW_SIZE = 4 * ALIGNMENT


def _sectors(raw: bytes) -> dict[str, str]:
    sectors: dict[str, str] = {}
    for lba in range(len(raw) // SECTOR_SIZE):
        sector = raw[lba * SECTOR_SIZE : (lba + 1) * SECTOR_SIZE]
        if any(sector):
            sectors[str(lba)] = base64.b64encode(sector).decode("ascii")
    return sectors


def build() -> dict[str, object]:
    """Write a template, provision a copy, and describe both."""
    partitions = [
        GptPartition("misc", 2048, 512 * 1024, partition_guid(IMAGE_VERSION, ROLE, "misc")),
        GptPartition("userdata", 4096, 256 * 1024, partition_guid(IMAGE_VERSION, ROLE, "userdata")),
    ]
    template = io.BytesIO(bytes(OLD_SIZE))
    write_gpt(
        template, disk_size=OLD_SIZE, guid=disk_guid(IMAGE_VERSION, ROLE), partitions=partitions
    )
    provisioned = io.BytesIO(template.getvalue() + bytes(NEW_SIZE - OLD_SIZE))
    provision_disk(provisioned, old_size=OLD_SIZE, new_size=NEW_SIZE, instance=INSTANCE, role=ROLE)
    return {
        "comment": "Generated by build_gpt_fixture.py; do not edit.",
        "instance": str(INSTANCE),
        "role": ROLE,
        "before": {"size": OLD_SIZE, "sectors": _sectors(template.getvalue())},
        "after": {"size": NEW_SIZE, "sectors": _sectors(provisioned.getvalue())},
    }


if __name__ == "__main__":
    OUTPUT.write_text(json.dumps(build(), indent=2, sort_keys=True) + "\n", encoding="utf-8")
